# Generated by Django 5.1.3 on 2025-01-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceprovider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
    ]
