# Generated by Django 5.1.3 on 2025-02-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0004_paymentattemptlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="insuranceprovider",
            name="provides_life",
            field=models.BooleanField(
                default=False, verbose_name="provides life insurance"
            ),
        ),
    ]
