# Generated by Django 5.1.3 on 2025-02-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0002_alter_travelinsurance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelinsurance",
            name="service_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="service fee",
            ),
        ),
        migrations.AddField(
            model_name="travelinsurance",
            name="tax",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="value added tax",
            ),
        ),
    ]
