# Generated by Django 5.1.3 on 2025-02-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0003_travelinsurance_service_fee_travelinsurance_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelinsurance",
            name="date_purchased",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date purchased"
            ),
        ),
    ]
