# Generated by Django 5.1.3 on 2025-02-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0004_travelinsurance_date_purchased"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelinsurance",
            name="status",
            field=models.CharField(
                choices=[
                    ("quote", "Quote"),
                    ("confirmed", "Confirmed"),
                    ("paid", "Paid"),
                    ("policy purchased", "Policy Purchased"),
                    ("cancelled before purchase", "Cancelled Before Purchase"),
                    ("cancelled before renewal", "Cancelled Before Renewal"),
                    ("expired", "Expired"),
                ],
                default="quote",
                max_length=50,
                verbose_name="status",
            ),
        ),
    ]
