# Generated by Django 5.1.3 on 2025-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel", "0005_alter_travelinsurance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelinsurance",
            name="last_payment_made_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last payment date"
            ),
        ),
    ]
