# Generated by Django 5.1.3 on 2025-02-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(max_length=3, null=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="country",
            name="nationality",
            field=models.CharField(
                max_length=100, null=True, verbose_name="nationality"
            ),
        ),
    ]
